version: '2'

services:
  backend:
    build: backend
    restart: unless-stopped
    environment:
        - SECRET_TOKEN=${BACKEND_SECRET_TOKEN}
    logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "10"
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: puppeteer_nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - "${NGINX_DATA_DIR}:/data/nginx-cache"
    ports:
      - 172.17.0.1:30666:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"