version: '2'

services:
  backend:
    build: backend
    expose:
     - 3000
  nginx:
    image: nginx:latest
    container_name: puppeteer_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 30666:80
