version: '2'

services:
  backend:
    build: backend
    restart: unless-stopped
    environment:
        - SECRET_TOKEN=testing
    expose:
     - 3000
    logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "10"
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: puppeteer_nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /tmp/nginx-cache:/data/nginx-cache
    ports:
      - 30666:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"